let lessons = [
    {
        "id": 1001,
        "subject": "Maths",
        "location": "Cambridge",
        "price": 50.00,
        "image": "images/Les01.png",
        "spaces": 5,
    },
     {
        "id": 1002,
        "subject": "English",
        "location": "Oxford",
        "price": 100.00,
        "image": "images/Les02.png",
        "spaces": 5,
    },
     {
        "id": 1003,
        "subject": "Science Explorers",
        "location": "Cambridge",
        "price": 50.00,
        "image": "images/Les03.png",
        "spaces": 5,
    },
     {
        "id": 1004,
        "subject": "Arabic",
        "location": "Cambridge",
        "price": 50.00,
        "image": "images/Les04.png",
        "spaces": 5,
    },
     {
        "id": 1005,
        "subject": "French",
        "location": "Oxford",
        "price": 100.00,
        "image": "images/Les05.png",
        "spaces": 5,
    },
     {
        "id": 1006,
        "subject": "Drawing and Animation",
        "location": "Cardiff",
        "price": 70.00,
        "image": "images/Les06.png",
        "spaces": 5,
    },
     {
        "id": 1007,
        "subject": "Music",
        "location": "Glasgow",
        "price": 20.00,
        "image": "images/Les07.png",
        "spaces": 5,
    },
     {
        "id": 1008,
        "subject": "Reading Club",
        "location": "Oxford",
        "price": 100.00,
        "image": "images/Les08.png",
        "spaces": 5,
    },
     {
        "id": 1009,
        "subject": "Film & Media",
        "location": "Bristol",
        "price": 150.00,
        "image": "images/Les09.png",
        "spaces": 5,
    },
     {
        "id": 1010,
        "subject": "Puzzle Zone",
        "location": "Edinburgh",
        "price": 35.00,
        "image": "images/Les10.png",
        "spaces": 5,
    }
];

